variables:
  - &alpine_image 'docker.io/alpine:3.19'
  - path: &docs_path
      - 'docs/**'

steps:
  docker-build-image:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: Dockerfile
      repo: vnpower/pixivfe
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      auto_tag: true
    when:
      branch: [ v2 ]
      event: [ tag, release, manual ]

  generate-docs:
    image: woodpeckerci/plugin-mkdocs:minimal
    settings:
      site_dir: build
      verbose: true
      pip_install_file: requirements.txt
    when:
      branch: [ v2 ]
      path: *docs_path
      event: [ push, tag, release, manual ]

  deploy-docs:
    image: codeberg.org/xfix/plugin-codeberg-pages-deploy:1
    settings:
      folder: build
      ssh_key:
        from_secret: DOCS_SSH_KEY
    when:
      branch: [ v2 ]
      path: *docs_path
      event: [ push, tag, release, manual ]
