steps:
  - name: docker-build-image
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: Dockerfile
      registry: https://docker.io
      repo: codeberg.org/VnPower/PixivFE
      platforms: linux/amd64,linux/arm64
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    when:
      branch: [ v2 ]
      event: [ tag, release ]
    
