steps:
  - name: docker-build-image
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: Dockerfile
      repo: vnpower/pixivfe
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    when:
      branch: [ v2 ]
      event: [ tag, release, manual ]
    
