services:
  pixivfe:
    container_name: pixivfe
    hostname: pixivfe
    image: vnpower/pixivfe:latest
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    ports:
      # Only specify 0.0.0.0 for host_ip if you are **not** using a reverse proxy
      - name: http
        target: 8282
        host_ip: 127.0.0.1
        published: 8282
        protocol: tcp
        app_protocol: http
    env_file:
      - path: .env
        required: true
    restart: unless-stopped
    cap_drop:
      - ALL
    read_only: true
    user: 10001:10001
    security_opt:
      - no-new-privileges:true
