project_id: 724667
preserve_hierarchy: true
files:
- source: i18n/locale/en/code.json
  translation: i18n/locale/%locale%/%original_file_name%
- source: i18n/locale/en/template.json
  translation: i18n/locale/%locale%/%original_file_name%
