variables:
  - &buildx_plugin 'woodpeckerci/plugin-docker-buildx:latest'

when:
  - event: [ tag, release, manual ]
    branch: [ v2 ]

steps:
  docker-build-image:
    image: *buildx_plugin
    settings:
      dockerfile: Dockerfile
      repo: vnpower/pixivfe
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      auto_tag: true
