variables:
  - &buildx_plugin 'woodpeckerci/plugin-docker-buildx:latest'
  - publish_logins: &publish_logins # Default DockerHub login
      - registry: https://index.docker.io/v1/
        username:
          from_secret: DOCKER_USERNAME
        password:
          from_secret: DOCKER_PASSWORD
  - path: &when_path
      # web source code
      - 'assets/**'
      # go source code
      - '**/*.go'
      - 'go.*'
      # Dockerfile changes
      - 'Dockerfile'
      # pipeline config changes
      - '.woodpecker/docker.yaml'

steps:
  release:
    image: *buildx_plugin
    settings:
      dockerfile: Dockerfile
      repo: vnpower/pixivfe
      logins: *publish_logins
      tag: [latest, '${CI_COMMIT_TAG}']
    when:
      - event: [ tag, release ]
        branch: [ v2 ]

  next:
    image: *buildx_plugin
    settings:
      dockerfile: Dockerfile
      repo: vnpower/pixivfe
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      tag: [next, 'next-${CI_COMMIT_SHA:0:10}']
    when:
      - event: [ push ]
        branch: [ v2 ]
        path: *when_path
