# -- Plugin to find vulnerabilities, misconfigurations, secrets, SBOM and more.
# ref: https://woodpecker-ci.org/plugins/Trivy
steps:
  trivy:
    image: aquasec/trivy:latest
    settings:
      exit-code: 1
      skip-dirs: doc/
      dir: .
      severity: MEDIUM,HIGH,CRITICAL
    when:
      - event: [ push, tag, release, manual ]
        branch: [ v2 ]
